ARG NODE_IMAGE=node:22-bookworm-slim
ARG NGINX_IMAGE=nginx:alpine
FROM ${NODE_IMAGE} AS build

WORKDIR /src
RUN corepack enable
COPY . .
RUN pnpm install --frozen-lockfile

ARG VITE_NEXUS_MEETING_INVITE_URL
ARG VITE_NEXUS_MEETING_SIGNAL_URL
ARG VITE_NEXUS_MEETING_HOST_SESSION_URL
ARG VITE_NEXUS_TURN_CREDENTIAL_URL
ARG VITE_NEXUS_WEB_APP_URL
ENV VITE_NEXUS_MEETING_ONLY=true
ENV VITE_NEXUS_MEETING_INVITE_URL=${VITE_NEXUS_MEETING_INVITE_URL}
ENV VITE_NEXUS_MEETING_SIGNAL_URL=${VITE_NEXUS_MEETING_SIGNAL_URL}
ENV VITE_NEXUS_MEETING_HOST_SESSION_URL=${VITE_NEXUS_MEETING_HOST_SESSION_URL}
ENV VITE_NEXUS_TURN_CREDENTIAL_URL=${VITE_NEXUS_TURN_CREDENTIAL_URL}
ENV VITE_NEXUS_WEB_APP_URL=${VITE_NEXUS_WEB_APP_URL}
RUN pnpm --filter @nexus/web build

FROM ${NGINX_IMAGE}

COPY deploy/pilot/web-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/apps/web/dist /usr/share/nginx/html

EXPOSE 8080
